---
# - name: customize /etc/environment
#   ansible.builtin.lineinfile:
#     dest: "/etc/environment"
#     state: present
#     regexp: "^{{ item.key }}="
#     line: "{{ item.key }}={{ item.value }}"
#   with_items: "{{ os_environment }}"

- name: Install general items
  community.general.homebrew: name={{ item }} state=present
  with_items:
    - go
    - gcc@5
  register: genins_output
- debug: var=genins_output 

- name: Install tfenv
  community.general.homebrew:
    name: tfenv
    state: present
  register: tfins_output
- debug: var=tfins_output.changed_pkgs 

- name: Install Latest TF
  ansible.builtin.shell: |
      tfenv install latest
      tfenv use latest
  register: tfenv_output
- debug: var=tfenv_output.stdout_lines 